### ISSUE TITLE
Invalid mnemonic generated

### ISSUE THREAD

**Issue by maslowalex** [ayrat555/ton#64]
Hello @ayrat555 , and thank you for your effort to build this library.

Looks like the `Ton.generate_mnemonic/0` function is generating invalid mnemonics. Maybe I doing something wrong, but when I creates the mnemonic, obtains the keypair, send some ton in maiinnet to the wallet I'm no longer being able to transfer funds neither to "log in" to the wallet using the mnemonic using Tonkeeper for example.

I'm also tried to validate the addresses using [tonlib-rs](https://github.com/ston-fi/tonlib-rs) and I got the message from the library when trying to use the mnemonic generated by mentioned function:

```
Error: Invalid passwordless mnemonic (first byte: 0x9B)
```

Any feedback on that matter is highly appreciated.

**Comment by pxp9** [comment]
Hey @maslowalex , is there a reason why you close this issue ??

**Comment by maslowalex** [comment]
> Hey [@maslowalex](https://github.com/maslowalex) , is there a reason why you close this issue ??

@pxp9 Hey! I closed mainly because of the lack of reaction, and inability to write the code that will do the job by myself.

**Comment by pxp9** [comment]
@maslowalex 

I was talking to @ayrat555 today and 

we are planning to refactor the library to allow for things and to have the status of Native ADHL.

We are gonna take inspiration of https://github.com/xssnick/tonutils-go

Help is welcomed!

Feel free to re-open the issue.
